exes: main-wor-ser main-wor-deser

main-wor-ser: main-wor-ser.c workers.c
	gcc -o main-wor-ser.exe main-wor-ser.c workers.c

main-wor-deser: main-wor-deser.c workers.c
	gcc -o main-wor-deser.exe main-wor-deser.c workers.c

clean:
	del main-wor-ser.exe main-wor-deser.exe
